GetSystemDateAndTime: 'src/soap/get_system_date_and_time.xml'
GetCapabilities: 'src/soap/get_capabilities.xml'
GetDeviceInformation: 'src/soap/get_device_information.xml'
GetScopes: 'src/soap/get_scopes.xml'
GetServices: 'src/soap/get_services.xml'
GetNetworkInterfaces: 'src/soap/get_network_interfaces.xml'
GetDNS: 'src/soap/get_dns.xml'
GetProfiles: 'src/soap/get_profiles.xml'
GetStreamUri: 'src/soap/get_stream_uri.xml'
GetSnapshotUri: 'src/soap/get_snapshot_uri.xml'
GetVideoSources: 'src/soap/get_video_sources.xml'
GetVideoSourceConfiguration: 'src/soap/get_video_source_configuration.xml'
GetAudioSourceConfiguration: 'src/soap/get_audio_source_configuration.xml'
GetProfile: 'src/soap/get_profile.xml'
GetMetadataConfigurationOptions: 'src/soap/get_metadata_configuration_options.xml'
GetMetadataConfiguration: 'src/soap/get_metadata_configuration.xml'
Subscribe: 'src/soap/subscribe.xml'
GetEventProperties: 'src/soap/get_event_properties.xml'
GetAudioSources: 'src/soap/get_audio_source_configuration.xml'
Renew: 'src/soap/renew.xml'
Unsubscribe: 'src/soap/unsubscribe.xml'
CreatePullPointSubscription: 'src/soap/create_pull_point_subscription.xml'
PullMessages: 'src/soap/pull_messages.xml'
PullMessagesNothing: 'src/soap/pull_messages_nothing.xml'