GetSystemDateAndTime: 'src/soap/get_system_date_and_time.xml'
GetCapabilities: 'src/soap/get_capabilities.xml'
GetDeviceInformation: 'src/soap/get_device_information.xml'
GetScopes: 'src/soap/get_scopes.xml'
GetServices: 'src/soap/get_services.xml'
GetNetworkInterfaces: 'src/soap/get_network_interfaces.xml'
GetDNS: 'src/soap/get_dns.xml'
GetProfiles: 'src/soap/get_profiles.xml'
GetStreamUri: 'src/soap/get_stream_uri.xml'
GetSnapshotUri: 'src/soap/get_snapshot_uri.xml'
GetVideoSources: 'src/soap/get_video_sources.xml'
GetVideoSourceConfiguration: 'src/soap/get_video_source_configuration.xml'
GetAudioSourceConfiguration: 'src/soap/get_audio_source_configuration.xml'
GetProfile: 'src/soap/get_profile.xml'